version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      cargo-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: cargo
    directory: /fuzz
    schedule:
      interval: weekly
    groups:
      fuzz-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]
    open-pull-requests-limit: 5
